export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
export const FETCH_USERS_COMPLETE = 'FETCH_USERS_COMPLETE';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_POSTS_REQUESTED = 'FETCH_POSTS_REQUESTED';
export const FETCH_POSTS_COMPLETE = 'FETCH_POSTS_COMPLETE';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
